#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
autorandr -c
$HOME/.config/polybar/launch.sh
pgrep -x lxsession > /dev/null || lxsession &
pgrep -x volumeicon > /dev/null || volumeicon &
feh --bg-fill /home/guido/Pictures/last.jpg & 
wmname LG3D
pgrep -x blueman-applet > /dev/null || blueman-applet &
pgrep -x dunst > /dev/null || dunst &
#pgrep -x xfce4-power-manager > /dev/null || xfce4-power-manager
xsetroot -cursor_name left_ptr

bspc monitor DP-0 -n 0 -d 1 2 3 4 5 6 7
bspc monitor eDP-1-1 -n 1 -d 1 2 3 4 5 6 7

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp follow=on desktop='^3'
bspc rule -a MEGAsync state=floating
bspc rule -a Pavucontrol state=floating rectangle=789x512
bspc rule -a Xfce4-appfinder state=floating rectangle=789x512
bspc rule -a Opera desktop='^2' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a "Microsoft Teams - Preview" desktop='^1'
bspc rule -a Telegram desktop='^6' follow=on
bspc rule -a Spotify desktop='^4' follow=on
bspc rule -a vlc desktop='^7' follow=on rectangle=789x512
bspc rule -a Steam state=floating desktop='^5' follow=on
bspc rule -a wine state=floating desktop='^5' follow=on
bspc rule -a Lutris state=floating desktop='^5' follow=on
bspc rule -a Pamac-manager state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Gthumb state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Screenkey manage=off
